### ISSUE TITLE
EnableGameStream has stopped working

### ISSUE THREAD

**Issue by Croustiflex** [Lakritzator/EnableGameStream#3]
> A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

Sorry your program is not working for me. 
GT750M  - W10

Thanks

**Comment by max20091** [comment]
You need to downgrade your GFE to ver 2 in order to make this tool work

**Comment by Lakritzator** [comment]
I was based upon the information in the forum I linked to in my readme, as there was no update since and I don't have working hardware to test with, there are no updates for this.
