### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by puddingepoch** [Lakritzator/EnableGameStream#5]
this does not work.

all fields besides device id are empty, clicking patch does nothing, stop service is greyed out and start service just closes the program.. there is no specific issue, just that nothing works

**Comment by Lakritzator** [comment]
Please read #4 

This was written ages ago, in my free time and provided as is.
I currently have no idea if I can fix it, as I don't have any hardware by hand where this runs, and I don't know when I got time for it.
